FROM python:3.7
RUN mkdir /app
WORKDIR /app
RUN apt-get update &&\
    apt-get install python3-dev default-libmysqlclient-dev  -y
ADD requirements.txt /app/
RUN pip install -r requirements.txt
ADD . /app/
CMD python hello.py