version: '3'

services:
  redis:
    image: redis:5
    restart: always
  app:
    image: mohamedsaeed/fly365:{TAG}
    restart: always
    ports:
      - "${APP_PORT}:8000"
    environment:
      - ENVIRONMENT
      - HOST
      - PORT
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
